<script setup lang="ts">
definePageMeta({
  layout: 'marketing',
});

useHead({
  link: [
    { rel: 'canonical', href: 'https://thinkaction.id/privacy' },
  ],
});

useSeoMeta({
  title: 'Privacy Policy | Thinkaction',
  description: 'Learn how Thinkaction collects, uses, and protects your personal information to keep your data safe and secure.',
  ogTitle: 'Privacy Policy | Thinkaction',
  ogType: 'website',
  ogSiteName: 'Thinkaction',
  ogDescription: 'Learn how Thinkaction collects, uses, and protects your personal information to keep your data safe and secure.',
});
</script>

<template>
  <section class="bg-slate-100 max-w-4xl mx-auto px-4 lg:px-8 py-8 rounded-xl shadow-xl mt-4">
    <header class="mb-14 text-center">
      <h1 class="text-2xl sm:text-4xl font-extrabold text-[#028F61]">
        Privacy Policy
      </h1>
    </header>

    <div class="space-y-12">
      <section>
        <h2
          class="text-xl font-bold text-gray-800 dark:text-gray-200 mb-4 pb-2 border-b border-gray-200 dark:border-gray-700"
        >
          1. Introduction
        </h2>
        <p class="text-gray-700 dark:text-gray-300 leading-relaxed">
          Welcome to Thinkaction ("we," "our," or "us") which operates the website https://www.thinkaction.id (the
          "Service"). This
          page informs you
          of our policies regarding the collection, use, and disclosure of personal data when you use our Service and
          the choices you have associated with that data.
        </p>
        <p class="text-gray-700 dark:text-gray-300 leading-relaxed mt-4">
          We use your data to provide and improve the Service. By using the Service, you agree to the collection and use
          of information in accordance with this policy.
        </p>
      </section>

      <section>
        <h2
          class="text-xl font-bold text-gray-800 dark:text-gray-200 mb-4 pb-2 border-b border-gray-200 dark:border-gray-700"
        >
          2. Definitions
        </h2>
        <ul class="list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300 ml-5">
          <li>
            <strong class="font-bold">Service:</strong> The website https://www.thinkaction.id operated by Thinkaction.
          </li>
          <li>
            <strong class="font-bold">Personal Data:</strong> Data about a living individual who can be identified
            from those data (or from those and other information either in our possession or likely to come into our
            possession).
          </li>
          <li>
            <strong class="font-bold">Usage Data:</strong> Data collected automatically, either generated by the use
            of the Service or from the Service infrastructure itself (e.g., the duration of a page visit).
          </li>
        </ul>
      </section>

      <section>
        <h2
          class="text-xl font-bold text-gray-800 dark:text-gray-200 mb-4 pb-2 border-b border-gray-200 dark:border-gray-700"
        >
          3. Information Collection and Use
        </h2>
        <p class="text-gray-700 dark:text-gray-300 leading-relaxed mb-4">
          We collect several different types of information for various purposes to provide and improve our Service to
          you.
        </p>

        <h3 class="text-lg font-bold text-gray-800 dark:text-gray-200 mb-3 mt-6">
          Types of Data Collected
        </h3>

        <h4 class="font-bold text-gray-700 dark:text-gray-300 mb-2 mt-4">
          Personal Data
        </h4>
        <p class="text-gray-700 dark:text-gray-300 leading-relaxed">
          While using our Service, we may ask you to provide us with certain personally identifiable information that
          can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but
          is not limited to:
        </p>
        <ul class="list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300 ml-5 mt-3">
          <li>Email address</li>
          <li>Cookies and Usage Data</li>
        </ul>

        <h4 class="font-bold text-gray-700 dark:text-gray-300 mb-2 mt-4">
          Usage Data
        </h4>
        <p class="text-gray-700 dark:text-gray-300 leading-relaxed">
          We may also collect information on how the Service is accessed and used ("Usage Data"). This Usage Data may
          include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser
          version, the pages of our Service that you visit, the time and date of your visit, the time spent on those
          pages, unique device identifiers and other diagnostic data.
        </p>
      </section>

      <section>
        <h2
          class="text-xl font-bold text-gray-800 dark:text-gray-200 mb-4 pb-2 border-b border-gray-200 dark:border-gray-700"
        >
          4. Use of Data
        </h2>
        <p class="text-gray-700 dark:text-gray-300 leading-relaxed mb-4">
          Thinkaction uses the collected data for various purposes:
        </p>
        <ul class="list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300 ml-5">
          <li>To provide and maintain the Service</li>
          <li>To notify you about changes to our Service</li>
          <li>To provide customer support</li>
          <li>To provide analysis or valuable information so that we can improve the Service</li>
          <li>To monitor the usage of the Service</li>
        </ul>
      </section>

      <section>
        <h2
          class="text-xl font-bold text-gray-800 dark:text-gray-200 mb-4 pb-2 border-b border-gray-200 dark:border-gray-700"
        >
          5. Tracking & Cookies Data
        </h2>
        <p class="text-gray-700 dark:text-gray-300 leading-relaxed mb-4">
          We use cookies and similar tracking technologies to track the activity on our Service and hold certain
          information.
        </p>
        <p class="text-gray-700 dark:text-gray-300 leading-relaxed">
          A cookie is a small file stored on your device. You can instruct your browser to refuse all cookies or to
          indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some
          portions of our Service.
        </p>
        <h4 class="font-bold text-gray-700 dark:text-gray-300 mb-2 mt-4">
          Examples of Cookies We Use:
        </h4>
        <ul class="list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300 ml-5 mt-3">
          <li>
            <strong class="font-bold">Session Cookies:</strong> We use Session Cookies to operate our Service.
          </li>
          <li>
            <strong class="font-bold">Preference Cookies:</strong> We use Preference Cookies to remember your
            preferences and various settings.
          </li>
          <li>
            <strong class="font-bold">Security Cookies:</strong> We use Security Cookies for security purposes.
          </li>
        </ul>
      </section>

      <section>
        <h2
          class="text-xl font-bold text-gray-800 dark:text-gray-200 mb-4 pb-2 border-b border-gray-200 dark:border-gray-700"
        >
          6. Contact Us
        </h2>
        <p class="text-gray-700 dark:text-gray-300 leading-relaxed">
          If you have any questions about this Privacy Policy, please contact us:
        </p>
        <ul class="list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300 ml-5 mt-3">
          <li>
            By email:
            <a
              href="mailto:support@thinkaction.id"
              class="text-blue-600 hover:underline dark:text-blue-400"
            >support@thinkaction.id</a>
          </li>
        </ul>
      </section>
    </div>
  </section>
</template>
